// js/topics.js
// Built-in topics. Your own games (the game creator) sit alongside these.

const T = (id, name, words) => ({ id, name, builtIn: true, words: words.split(",").map((w) => w.trim()).filter(Boolean) });

export const TOPICS = [
  T("animals", "Animals", "Elephant, Monkey, Kangaroo, Penguin, Snake, Chicken, Giraffe, Crab, Frog, Horse, Shark, Octopus, Gorilla, Butterfly, Duck, Cat, Dog, Lion, Rabbit, Bear, Owl, Crocodile, Spider, Flamingo, Sloth, Dolphin, Bee, Pig, Cow, Seal, Tortoise, Squirrel, Eagle, Camel, Bat, Peacock, Mouse, Donkey, Parrot, Worm"),
  T("actions", "Actions", "Brushing teeth, Swimming, Skiing, Juggling, Riding a bike, Playing guitar, Taking a selfie, Changing a nappy, Mowing the lawn, Walking a dog, Bowling, Fishing, Boxing, Knitting, Painting a wall, Driving, Flying a kite, Doing yoga, Surfing, Climbing a ladder, Playing darts, Hula hooping, Blowing bubbles, Milking a cow, Ironing, Sneezing, Rowing a boat, Skipping, Tightrope walking, Baking a cake, Washing up, Taking a shower, Sleepwalking, Directing traffic, Conducting an orchestra, Karate, Ice skating, Hitchhiking, Parachuting, Moonwalking"),
  T("jobs", "Jobs", "Doctor, Firefighter, Pilot, Chef, Teacher, Police officer, Dentist, Hairdresser, Farmer, Builder, Plumber, Magician, Clown, Astronaut, Lifeguard, Photographer, Waiter, Referee, Postman, Taxi driver, Surgeon, DJ, Mechanic, Lumberjack, Beekeeper, Detective, Pirate, Zookeeper, Painter, Ballet dancer, Weightlifter, Personal trainer, Barista, Butcher, Scientist, Judge, Security guard, Window cleaner, Tattoo artist, Sailor"),
  T("sports", "Sports", "Football, Tennis, Golf, Basketball, Cricket, Rugby, Swimming, Boxing, Darts, Snooker, Skiing, Surfing, Skateboarding, Cycling, Archery, Fencing, Gymnastics, High jump, Javelin, Weightlifting, Wrestling, Table tennis, Badminton, Ice hockey, Baseball, Bowling, Sumo, Rowing, Diving, Horse riding, Formula 1, Marathon, Rock climbing, Volleyball, Karate, Curling, Water polo, Bobsleigh, Trampolining, Kayaking"),
  T("films", "Films", "Titanic, Jaws, Frozen, Star Wars, Harry Potter, The Lion King, Toy Story, Jurassic Park, Home Alone, Finding Nemo, Shrek, The Matrix, Rocky, Ghostbusters, Grease, Mamma Mia, Top Gun, Spider-Man, Batman, Superman, Up, Cars, The Godfather, Pirates of the Caribbean, Avatar, Mary Poppins, E.T., Back to the Future, Ratatouille, Minions, King Kong, Karate Kid, Mission Impossible, James Bond, Indiana Jones, The Wizard of Oz, Frankenstein, Dirty Dancing, Madagascar, Inside Out"),
  T("food", "Food and drink", "Spaghetti, Pizza, Banana, Ice cream, Popcorn, Sushi, Burger, Hot dog, Pancakes, Corn on the cob, Watermelon, Lemon, Chilli, Onion, Coconut, Candyfloss, Toast, Soup, Taco, Doughnut, Jelly, Cheese, Milkshake, Coffee, Tea, Champagne, Chewing gum, Lollipop, Pineapple, Birthday cake, Fish and chips, Boiled egg, Crisps, Noodles, Chocolate, Carrot, Grapes, Curry, Kebab, Porridge"),
  T("places", "Places", "Beach, Desert, Jungle, Library, Hospital, Airport, Cinema, Zoo, Gym, Castle, Farm, Circus, Supermarket, Theme park, Swimming pool, Igloo, Volcano, Prison, Haunted house, Space station, Dentist, Hairdresser, Bowling alley, Nightclub, Church, Car wash, Campsite, Ski slope, Museum, Stadium, Restaurant, Lighthouse, Submarine, Treehouse, Waterfall, Fairground, Train station, Casino, Laundrette, Petrol station"),
];
