// engine/checkouts.js
// Checkout suggestions.
//   - Double out with three darts in hand uses the curated table below (standard pro routes).
//   - Everything else (fewer darts left mid-visit, straight out, not yet checked in)
//     is generated by searching every route and picking the most sensible one.

import { SCORING_DARTS, parseDart, dartLabel } from "./board.js";
import { CHECK_OUT, minDartsToFinish, isBustRemaining } from "./rules.js";

// Three-dart double-out routes. Carried over from the original app.
const TABLE = {
  170: "T20 T20 BULL", 167: "T20 T19 BULL", 164: "T19 T19 BULL", 161: "T20 T17 BULL",
  160: "T20 T20 D20", 158: "T20 T20 D19", 157: "T19 T20 D20", 156: "T20 T20 D18",
  155: "T20 T19 D19", 154: "T20 T18 D20", 153: "T20 T19 D18", 152: "T20 T20 D16",
  151: "T20 T17 D20", 150: "T20 T18 D18", 149: "T20 T19 D16", 148: "T20 T20 D14",
  147: "T20 T17 D18", 146: "T20 T18 D16", 145: "T20 T15 D20", 144: "T20 T20 D12",
  143: "T20 T17 D16", 142: "T20 T14 D20", 141: "T20 T15 D18", 140: "T20 T16 D16",
  139: "T20 T13 D20", 138: "T20 T16 D15", 137: "T18 T17 D16", 136: "T20 T20 D8",
  135: "T20 T13 D18", 134: "T20 T14 D16", 133: "T20 T19 D8", 132: "T20 T16 D12",
  131: "T20 T13 D16", 130: "T20 T18 D8", 129: "T19 T16 D12", 128: "T20 T20 D4",
  127: "T20 T17 D8", 126: "T19 19 BULL", 125: "T20 T19 D4", 124: "T20 T16 D8",
  123: "T20 T13 D12", 122: "T18 18 BULL", 121: "T19 14 BULL", 120: "T20 20 D20",
  119: "T20 19 D20", 118: "T20 18 D20", 117: "T20 17 D20", 116: "T20 16 D20",
  115: "T20 15 D20", 114: "T20 14 D20", 113: "T20 13 D20", 112: "T20 12 D20",
  111: "T20 19 D16", 110: "T20 10 D20", 109: "T19 12 D20", 108: "T20 16 D16",
  107: "T19 10 D20", 106: "T20 10 D18", 105: "T20 13 D16", 104: "T20 12 D16",
  103: "T19 10 D18", 102: "T20 10 D16", 101: "T17 10 D20", 100: "T20 D20",
  99: "T19 10 D16", 98: "T20 D19", 97: "T19 D20", 96: "T20 D18", 95: "T19 D19",
  94: "T18 D20", 93: "T19 D18", 92: "T20 D16", 91: "T17 D20", 90: "T18 D18",
  89: "T19 D16", 88: "T16 D20", 87: "T17 D18", 86: "T18 D16", 85: "T15 D20",
  84: "T16 D18", 83: "T17 D16", 82: "T14 D20", 81: "T15 D18", 80: "T16 D16",
  79: "T13 D20", 78: "T18 D12", 77: "T15 D16", 76: "T20 D8", 75: "T13 D18",
  74: "T14 D16", 73: "T19 D8", 72: "T16 D12", 71: "T13 D16", 70: "T18 D8",
  69: "19 BULL", 68: "T20 D4", 67: "T17 D8", 66: "T10 D18", 65: "T19 D4",
  64: "T16 D8", 63: "T13 D12", 62: "T10 D16", 61: "T15 D8", 60: "20 D20",
  59: "19 D20", 58: "18 D20", 57: "17 D20", 56: "16 D20", 55: "15 D20",
  54: "14 D20", 53: "13 D20", 52: "12 D20", 51: "19 D16", 50: "10 D20",
  49: "17 D16", 48: "16 D16", 47: "15 D16", 46: "6 D20", 45: "13 D16",
  44: "12 D16", 43: "3 D20", 42: "10 D16", 41: "9 D16", 40: "D20",
  39: "7 D16", 38: "D19", 37: "5 D16", 36: "D18", 35: "3 D16", 34: "D17",
  33: "1 D16", 32: "D16", 31: "15 D8", 30: "D15", 29: "13 D8", 28: "D14",
  27: "11 D8", 26: "D13", 25: "9 D8", 24: "D12", 23: "7 D8", 22: "D11",
  21: "5 D8", 20: "D10", 19: "3 D8", 18: "D9", 17: "1 D8", 16: "D8",
  15: "7 D4", 14: "D7", 13: "5 D4", 12: "D6", 11: "3 D4", 10: "D5",
  9: "1 D4", 8: "D4", 7: "3 D2", 6: "D3", 5: "1 D2", 4: "D2", 3: "1 D1", 2: "D1",
};

export const CHECKOUT_TABLE = Object.freeze(
  Object.fromEntries(Object.entries(TABLE).map(([k, v]) => [Number(k), v.split(" ").map(parseDart)]))
);

// ---------------------------------------------------------------------------
// Route generator
// ---------------------------------------------------------------------------
// Lower cost = better. Fewest darts wins unless an extra dart buys a far nicer
// double (e.g. 50 with two darts: "10, D20" rather than going for the bull).

const EXTRA_DART_COST = 1.5;
const DOUBLE_PREFERENCE = { 20: 0, 16: 0.05, 18: 0.4, 8: 0.5, 10: 0.6, 12: 0.6, 14: 0.9, 4: 1, 6: 1, 2: 1.4 };

function setupCost(d) {
  if (d.seg === 25) return d.mult === 2 ? 3.2 : 2.6;
  if (d.mult === 1) return 0.2; // every single is the same size, so no preference
  if (d.mult === 3) return 1 + (20 - d.seg) * 0.03; // you're aiming at T20 anyway
  return 3; // using a double to set up is a last resort
}

function finishCost(d, checkOut) {
  if (checkOut === CHECK_OUT.STRAIGHT) {
    if (d.seg === 25) return d.mult === 2 ? 2.4 : 1.8;
    if (d.mult === 1) return 0.2 + (20 - d.seg) * 0.005;
    if (d.mult === 3) return 1 + (20 - d.seg) * 0.03;
    return 1.2 + (20 - d.seg) * 0.02;
  }
  if (d.seg === 25) return 2.5;
  return DOUBLE_PREFERENCE[d.seg] ?? 1.6 + (20 - d.seg) * 0.02;
}

function finishers(checkOut) {
  return checkOut === CHECK_OUT.STRAIGHT ? SCORING_DARTS : SCORING_DARTS.filter((d) => d.mult === 2);
}

const routeMemo = new Map();

function generateRoute(remaining, checkOut, dartsLeft, needsDoubleIn) {
  const key = `${remaining}|${checkOut}|${dartsLeft}|${needsDoubleIn ? 1 : 0}`;
  if (routeMemo.has(key)) return routeMemo.get(key);

  const minDarts = minDartsToFinish(remaining, checkOut, needsDoubleIn);
  let best = null;
  let bestCost = Infinity;
  const fin = finishers(checkOut);
  const setups = SCORING_DARTS;

  const consider = (route) => {
    let cost = (route.length - minDarts) * EXTRA_DART_COST;
    for (let i = 0; i < route.length - 1; i++) cost += setupCost(route[i]);
    cost += finishCost(route[route.length - 1], checkOut);
    if (cost < bestCost) {
      bestCost = cost;
      best = route;
    }
  };

  const firstOk = (d) => !needsDoubleIn || d.mult === 2;
  const stillAlive = (rem) => rem > 0 && !isBustRemaining(rem, checkOut);

  for (let k = minDarts; k <= dartsLeft; k++) {
    if (k === 1) {
      for (const f of fin) if (f.value === remaining && firstOk(f)) consider([f]);
    } else if (k === 2) {
      for (const a of setups) {
        if (!firstOk(a) || !stillAlive(remaining - a.value)) continue;
        for (const f of fin) if (a.value + f.value === remaining) consider([a, f]);
      }
    } else if (k === 3) {
      for (const a of setups) {
        if (!firstOk(a) || !stillAlive(remaining - a.value)) continue;
        for (const b of setups) {
          const left = remaining - a.value - b.value;
          if (!stillAlive(left)) continue;
          for (const f of fin) if (f.value === left) consider([a, b, f]);
        }
      }
    }
  }

  routeMemo.set(key, best);
  return best;
}

// The suggested route as an array of darts, or null if there's no finish on.
export function suggestCheckout(remaining, { checkOut = CHECK_OUT.DOUBLE, dartsLeft = 3, checkedIn = true } = {}) {
  const r = Number(remaining);
  if (!Number.isInteger(r) || r < 1 || dartsLeft < 1) return null;
  const needsDoubleIn = !checkedIn;
  if (minDartsToFinish(r, checkOut, needsDoubleIn) > dartsLeft) return null;

  if (checkOut === CHECK_OUT.DOUBLE && !needsDoubleIn) {
    const fromTable = CHECKOUT_TABLE[r];
    if (fromTable && fromTable.length <= dartsLeft) return fromTable;
  }
  return generateRoute(r, checkOut, dartsLeft, needsDoubleIn);
}

export function routeLabels(route) {
  return route ? route.map(dartLabel) : [];
}
