// js/words.js
// Words to describe, by theme, each with a vague hint for the impostor
// ("Word:Hint"). Hints point roughly at the topic without giving it away.
// Duplicates are removed when the list is built.

const THEMES = {
  Animals:
    "Dog:Loyal, Cat:Independent, Elephant:Memory, Giraffe:Tall, Penguin:Tuxedo, Kangaroo:Pouch, Octopus:Ink, Shark:Fin, Dolphin:Clever, Whale:Enormous, Lion:Pride, Tiger:Stripes, Zebra:Black and white, Panda:Bamboo, Koala:Eucalyptus, Sloth:Slow, Crocodile:Swamp, Flamingo:Pink, Owl:Night, Eagle:Soaring, Parrot:Talkative, Peacock:Showing off, Camel:Hump, Hippo:River, Rhino:Horn, Gorilla:Strong, Chimpanzee:Cousin, Squirrel:Nuts, Hedgehog:Spiky, Badger:Burrow, Fox:Sly, Wolf:Howl, Bear:Hibernate, Polar bear:Arctic, Moose:Antlers, Deer:Forest, Rabbit:Carrots, Hamster:Wheel, Guinea pig:Squeak, Goldfish:Bowl, Jellyfish:Sting, Starfish:Five, Seahorse:Curly, Crab:Sideways, Lobster:Claws, Snail:Shell, Spider:Web, Scorpion:Tail, Bee:Buzz, Butterfly:Wings, Ant:Colony, Mosquito:Itchy, Ladybird:Spots, Bat:Upside down, Frog:Pond, Toad:Warty, Tortoise:Ancient, Turtle:Beach, Snake:Slither, Lizard:Sunbathing, Chameleon:Camouflage, Horse:Gallop, Donkey:Stubborn, Cow:Field, Pig:Mud, Sheep:Wool, Goat:Climber, Chicken:Eggs, Duck:Quack, Swan:Graceful, Goose:Honk, Pigeon:City, Seagull:Chips, Robin:Winter, Crow:Clever bird, Hummingbird:Hovering, Ostrich:Fast runner, Emu:Australia, Llama:Spit, Alpaca:Fluffy, Raccoon:Bins, Skunk:Smelly, Otter:Holding hands, Beaver:Dam, Seal:Flippers, Walrus:Tusks, Meerkat:Lookout, Cheetah:Fastest, Leopard:Spotted, Jaguar:Rainforest, Armadillo:Armour, Platypus:Odd, Pelican:Beak pouch, Woodpecker:Tapping, Vulture:Circling, Hyena:Laughing, Mole:Underground, Worm:Soil, Stingray:Flat, Piranha:Teeth, Salmon:Upstream, Clownfish:Anemone, Orca:Killer",
  Food:
    "Pizza:Slices, Burger:Bun, Sushi:Rice rolls, Pasta:Italian, Spaghetti:Twirling, Lasagne:Layers, Taco:Crunchy shell, Burrito:Wrapped, Curry:Spicy, Kebab:Late night, Fish and chips:Seaside, Sandwich:Lunchbox, Hot dog:Stadium, Pancake:Flip, Waffle:Grid, Croissant:Flaky, Doughnut:Hole, Cupcake:Icing, Brownie:Gooey, Cheesecake:Creamy, Ice cream:Cone, Chocolate:Melts, Popcorn:Cinema, Crisps:Crunchy, Nachos:Cheesy, Salad:Healthy, Soup:Spoon, Omelette:Folded, Scrambled eggs:Breakfast, Bacon:Sizzle, Sausage:Banger, Toast:Crumbs, Porridge:Oats, Cereal:Bowl, Yoghurt:Pot, Cheese:Mouse, Butter:Spread, Honey:Sticky, Jam:Jar, Peanut butter:Nutty spread, Banana:Yellow, Apple:Crunchy fruit, Orange:Peel, Lemon:Sour, Strawberry:Summer, Watermelon:Seeds, Pineapple:Tropical, Mango:Juicy, Grapes:Bunch, Cherry:Stone, Coconut:Hairy, Avocado:Toast topping, Tomato:Red, Potato:Mash, Carrot:Orange veg, Broccoli:Tiny trees, Onion:Tears, Garlic:Vampires, Mushroom:Fungus, Sweetcorn:Kernels, Peas:Pods, Chilli:Hot, Cucumber:Cool, Pumpkin:Halloween, Rice:Grain, Noodles:Slurp, Dumplings:Steamed, Spring roll:Starter, Paella:Spain, Risotto:Stirring, Roast dinner:Sunday, Yorkshire pudding:Batter, Gravy:Pour, Ketchup:Red sauce, Mustard:Yellow sauce, Mayonnaise:White sauce, Coffee:Caffeine, Tea:Kettle, Hot chocolate:Marshmallows, Milkshake:Straw, Smoothie:Blended, Lemonade:Fizzy, Orange juice:Morning, Cola:Bubbles, Champagne:Celebration, Wine:Grapes, Beer:Pint, Cocktail:Umbrella, Birthday cake:Candles, Gingerbread:Christmas, Marshmallow:Squishy, Candyfloss:Fairground, Lollipop:Stick, Jelly:Wobbly, Trifle:Layered pudding, Scone:Cream tea, Bagel:Ring, Pretzel:Twisted, Goulash:Paprika, Pie:Crust, Quiche:Eggy, Falafel:Chickpeas, Hummus:Dip, Guacamole:Green dip",
  Places:
    "Beach:Sand, Desert:Dry, Jungle:Vines, Forest:Trees, Mountain:Peak, Volcano:Lava, Island:Surrounded, Cave:Dark, Waterfall:Splash, River:Flowing, Lake:Still water, Glacier:Ice, Farm:Tractor, Zoo:Cages, Aquarium:Tanks, Museum:Exhibits, Library:Quiet, School:Lessons, University:Degree, Hospital:Ward, Airport:Departures, Train station:Platform, Bus stop:Waiting, Petrol station:Pump, Supermarket:Trolley, Shopping centre:Escalators, Cinema:Big screen, Theatre:Curtain, Stadium:Crowd, Gym:Sweat, Swimming pool:Chlorine, Bowling alley:Strike, Casino:Chips, Nightclub:Dancing, Pub:Pints, Restaurant:Menu, Café:Latte, Bakery:Fresh bread, Butcher:Meat, Hairdresser:Scissors, Barber:Fade, Post office:Parcels, Bank:Money, Police station:Cells, Fire station:Pole, Prison:Bars, Castle:Moat, Palace:Royalty, Church:Bells, Cathedral:Spire, Lighthouse:Coast, Harbour:Boats, Bridge:Crossing, Tunnel:Underneath, Motorway:Fast lane, Roundabout:Circle, Car park:Ticket, Playground:Swings, Park:Grass, Garden:Flowers, Greenhouse:Glass, Allotment:Vegetables, Campsite:Tents, Caravan park:Holiday, Hotel:Check-in, Hostel:Bunk beds, Spa:Relax, Sauna:Steam, Ski resort:Slopes, Theme park:Rollercoaster, Water park:Slides, Circus:Big top, Fairground:Rides, Market:Stalls, Car wash:Soapy, Launderette:Spin, Laboratory:Experiments, Factory:Production, Office:Desk, Warehouse:Boxes, Construction site:Hard hats, Scrapyard:Old cars, Graveyard:Headstones, Haunted house:Spooky, Space station:Orbit, Submarine:Deep, Treehouse:Branches, Igloo:Snow blocks, Attic:Dusty, Basement:Downstairs, Kitchen:Cooking, Bathroom:Tiles, Bedroom:Sleep, Garage:Tools, Balcony:Outside, Rooftop:High up, Escape room:Puzzles, Laser tag arena:Vests",
  Jobs:
    "Doctor:Prescription, Nurse:Care, Dentist:Drill, Vet:Pets, Pilot:Cockpit, Flight attendant:Aisle, Chef:Kitchen, Waiter:Tray, Teacher:Classroom, Police officer:Uniform, Firefighter:Hose, Paramedic:Emergency, Soldier:Army, Astronaut:Space, Scientist:Experiments, Farmer:Fields, Builder:Bricks, Plumber:Pipes, Electrician:Wires, Mechanic:Engine, Taxi driver:Meter, Bus driver:Route, Lorry driver:Long haul, Postman:Letters, Lifeguard:Whistle, Librarian:Shush, Judge:Gavel, Lawyer:Court, Accountant:Numbers, Banker:City, Journalist:Headlines, Photographer:Lens, Artist:Canvas, Musician:Instrument, DJ:Decks, Actor:Stage, Magician:Tricks, Clown:Red nose, Comedian:Jokes, Dancer:Moves, Singer:Voice, Footballer:Pitch, Referee:Whistle blower, Coach:Tactics, Personal trainer:Reps, Tattoo artist:Ink, Florist:Bouquet, Baker:Oven, Fisherman:Nets, Lumberjack:Axe, Miner:Underground, Architect:Blueprints, Engineer:Design, Programmer:Code, Game designer:Levels, Streamer:Live chat, Influencer:Followers, YouTuber:Subscribe, Detective:Clues, Spy:Secrets, Security guard:Patrol, Bouncer:Door, Zookeeper:Feeding time, Beekeeper:Hives, Gardener:Hedges, Cleaner:Spotless, Receptionist:Front desk, Estate agent:Viewings, Salesman:Deal, Cashier:Till, Barista:Espresso, Bartender:Pouring, Sommelier:Tasting, Pharmacist:Pills, Surgeon:Operating, Psychologist:Mind, Archaeologist:Digging, Astronomer:Telescope, Meteorologist:Forecast, Pirate:Treasure, Knight:Armour, King:Throne, Queen:Crown, President:Office, Prime minister:Number Ten, Mayor:Town hall, Priest:Sermon, Nun:Convent, Monk:Robes, Shepherd:Flock, Blacksmith:Anvil, Tailor:Measurements, Carpenter:Wood, Window cleaner:Squeegee, Chimney sweep:Soot, Stuntman:Danger, Racing driver:Pit stop",
  Objects:
    "Toothbrush:Bristles, Toothpaste:Minty, Hairdryer:Hot air, Mirror:Reflection, Towel:Drying, Soap:Bubbles, Shampoo:Lather, Razor:Shave, Umbrella:Rain, Wallet:Cards, Keys:Unlock, Backpack:Straps, Suitcase:Wheels, Watch:Wrist, Glasses:Lenses, Sunglasses:Bright, Phone:Calls, Laptop:Portable, Tablet:Touchscreen, Headphones:Music, Remote control:Channels, Television:Programmes, Fridge:Cold, Freezer:Frozen, Microwave:Ping, Oven:Baking, Toaster:Pop up, Kettle:Boiling, Blender:Whizz, Dishwasher:Plates, Washing machine:Laundry, Vacuum cleaner:Suction, Iron:Creases, Ironing board:Flat surface, Broom:Sweep, Mop:Wet floor, Bucket:Handle, Ladder:Rungs, Hammer:Nails, Screwdriver:Twist, Drill:Holes, Saw:Cutting, Tape measure:Length, Torch:Beam, Candle:Wick, Lamp:Shade, Light bulb:Idea, Clock:Ticking, Alarm clock:Wake up, Calendar:Dates, Pen:Ink, Pencil:Sharpen, Rubber:Mistakes, Scissors:Snip, Stapler:Paper, Glue:Sticky, Sellotape:Roll, Paperclip:Bent wire, Notebook:Pages, Envelope:Seal, Stamp:Postage, Map:Directions, Globe:Spinning, Book:Chapters, Newspaper:Headlines, Magazine:Glossy, Bin:Rubbish, Bin bag:Plastic, Plate:Dinner, Bowl:Cereal, Cup:Saucer, Mug:Handle, Fork:Prongs, Knife:Sharp, Spoon:Soup, Chopsticks:Pair, Frying pan:Sizzle, Saucepan:Boil, Kettlebell:Swing, Pillow:Soft, Blanket:Cosy, Duvet:Cover, Mattress:Springs, Sofa:Lounging, Armchair:Comfy, Wardrobe:Hangers, Chest of drawers:Socks, Bookshelf:Novels, Curtains:Window, Carpet:Floor, Doormat:Welcome, Letterbox:Post, Doorbell:Ding dong, Padlock:Combination, Safe:Valuables, Piggy bank:Savings, Trophy:Winner, Medal:Podium, Balloon:Party, Kite:Windy day, Yo-yo:String, Rubik's cube:Colours, Teddy bear:Cuddle, Doll:Toy, Jigsaw puzzle:Pieces, Dice:Roll, Playing cards:Deck, Chess board:Squares, Paintbrush:Strokes, Easel:Artist stand, Fishing rod:Reel, Tent:Camping, Sleeping bag:Zip, Compass:North, Binoculars:Far away, Telescope:Stars, Microscope:Tiny, Magnifying glass:Bigger, Thermometer:Temperature, Plaster:Cut, Crutches:Broken leg, Wheelchair:Wheels, Stethoscope:Heartbeat",
  Sport:
    "Football:Goal, Rugby:Scrum, Cricket:Wicket, Tennis:Racket, Golf:Hole in one, Basketball:Hoop, Baseball:Bat, Ice hockey:Puck, Volleyball:Net, Badminton:Shuttlecock, Table tennis:Paddle, Snooker:Cue, Darts:Oche, Boxing:Gloves, Wrestling:Ring, Karate:Black belt, Judo:Throws, Fencing:Sword, Archery:Arrows, Swimming:Lengths, Diving:Board, Surfing:Waves, Sailing:Wind, Rowing:Oars, Canoeing:Paddle boat, Skiing:Slopes, Snowboarding:Tricks, Ice skating:Rink, Skateboarding:Ramps, BMX:Stunts, Cycling:Pedals, Marathon:Miles, Sprint:Fast, Hurdles:Jumping, High jump:Bar, Long jump:Sandpit, Pole vault:Bending, Javelin:Throw, Shot put:Heavy ball, Gymnastics:Flexible, Trampolining:Bouncing, Rock climbing:Grip, Bungee jumping:Elastic, Skydiving:Parachute, Paragliding:Floating, Horse racing:Jockey, Formula 1:Pit lane, Rally:Gravel, Motocross:Mud, Bowling:Pins, Pool:Pockets, Mini golf:Windmill, Frisbee:Disc, Dodgeball:Duck, Tug of war:Rope, Sack race:Hop, Egg and spoon race:Balance, Hide and seek:Counting, Tag:It, Musical chairs:Scramble, Hopscotch:Chalk, Chess:Checkmate, Poker:Bluff, Bingo:Numbers, Karaoke:Microphone, Charades:Acting, Monopoly:Property, Scrabble:Letters, Jenga:Tower, Twister:Spinner, Esports:Gaming, Paintball:Splat, Laser tag:Beams, Yoga:Stretch, Pilates:Core, Weightlifting:Barbell, Sumo:Heavyweights, Polo:Horseback, Water polo:Pool game, Curling:Stones, Bobsleigh:Ice track, Luge:Sled, Triathlon:Three events, Parkour:Freerunning, Kayaking:Rapids, Scuba diving:Oxygen, Snorkelling:Mask, Fishing:Bait, Hunting:Camouflage",
  Transport:
    "Car:Four wheels, Bus:Stops, Train:Tracks, Tram:Overhead wires, Taxi:Fare, Bicycle:Pedals, Motorbike:Helmet, Scooter:Kick, Electric scooter:Battery, Skateboard:Deck, Roller skates:Wheels, Lorry:Cargo, Van:Deliveries, Tractor:Farm, Digger:Scoop, Crane:Lifting, Forklift:Pallets, Ambulance:Siren, Fire engine:Ladder, Police car:Blue lights, Limousine:Long, Sports car:Speedy, Caravan:Towing, Camper van:Road trip, Ice cream van:Jingle, Double-decker bus:Upstairs, Underground:Tube, Monorail:Single rail, Cable car:Mountain, Ski lift:Chairs, Helicopter:Rotors, Aeroplane:Wings, Jet:Supersonic, Hot air balloon:Basket, Blimp:Floating, Glider:Silent, Rocket:Launch, Space shuttle:Orbit, Satellite:Signal, Ship:Ocean, Cruise ship:Holiday, Ferry:Crossing, Yacht:Luxury, Speedboat:Wake, Canoe:Paddle, Kayak:River, Rowing boat:Oars, Pedalo:Foot powered, Raft:Logs, Submarine:Periscope, Jet ski:Spray, Hovercraft:Cushion, Gondola:Venice, Rickshaw:Pulled, Tuk-tuk:Three wheels, Horse and cart:Old fashioned, Sledge:Snow, Snowmobile:Tracks, Segway:Balance, Unicycle:One wheel, Tank:Armour, Golf cart:Course, Go-kart:Little racer, Dune buggy:Sand, Quad bike:Four wheeler, Steam train:Smoke, Bullet train:Japan, Escalator:Moving stairs, Lift:Floors, Travelator:Airport walkway",
  Nature:
    "Rainbow:Colours, Thunderstorm:Rumble, Lightning:Flash, Tornado:Spinning, Hurricane:Storm, Snowflake:Unique, Snowman:Carrot nose, Blizzard:Whiteout, Fog:Misty, Hailstone:Pellets, Sunrise:Morning, Sunset:Evening, Moon:Night sky, Full moon:Werewolf, Star:Twinkle, Shooting star:Wish, Comet:Tail, Planet:Orbit, Galaxy:Milky, Black hole:Gravity, Eclipse:Shadow, Northern lights:Aurora, Earthquake:Shaking, Tsunami:Wave, Avalanche:Snow slide, Wildfire:Flames, Flood:Water rising, Drought:No rain, Heatwave:Scorching, Puddle:Splash, Icicle:Dripping, Rain:Wet, Wind:Breeze, Cloud:Fluffy, Sand dune:Desert, Quicksand:Sinking, Coral reef:Colourful, Rainforest:Humid, Swamp:Boggy, Meadow:Wildflowers, Hill:Slope, Valley:Between, Canyon:Deep, Cliff:Edge, Pebble:Smooth, Rock:Hard, Diamond:Sparkle, Gold:Precious, Crystal:Clear, Fossil:Ancient, Dinosaur:Extinct, Tree:Bark, Oak tree:Acorns, Palm tree:Tropical, Christmas tree:Baubles, Cactus:Prickly, Sunflower:Tall flower, Rose:Thorns, Daisy:Chain, Tulip:Holland, Dandelion:Blow, Mushroom ring:Fairies, Leaf:Green, Acorn:Squirrel food, Pinecone:Scales, Seaweed:Slimy, Moss:Damp, Bonfire:Guy Fawkes, Campfire:Marshmallows, Smoke:Grey, Tide:In and out, Wave:Surf, Whirlpool:Swirl, Geyser:Eruption, Hot spring:Warm water, Oasis:Desert water, Iceberg:Tip, Mud:Messy, Seasons:Four, Autumn:Falling leaves, Spring:Blossom, Summer:Sunshine, Winter:Frost",
  Landmarks:
    "Eiffel Tower:Paris, Big Ben:Chimes, Statue of Liberty:Torch, Great Wall of China:Long, Pyramids:Egypt, Colosseum:Rome, Leaning Tower of Pisa:Tilted, Taj Mahal:India, Stonehenge:Stones, Mount Everest:Summit, Grand Canyon:Arizona, Niagara Falls:Border, Sydney Opera House:Sails, Golden Gate Bridge:San Francisco, Tower Bridge:Thames, Buckingham Palace:Guards, London Eye:Wheel, Hollywood sign:Letters, Las Vegas:Strip, Disneyland:Mouse, Venice:Canals, Machu Picchu:Peru, Christ the Redeemer:Rio, Mount Rushmore:Faces, Hungarian Parliament:Danube, Chain Bridge:Budapest, Lake Balaton:Hungary, Sahara:Sand sea, Amazon:River, North Pole:Santa, South Pole:Penguins, Antarctica:Coldest, Loch Ness:Monster, Area 51:Aliens, Bermuda Triangle:Mystery, Atlantis:Lost city, Titanic:Iceberg, Moon landing:One small step, Olympics:Rings, World Cup:Trophy, Wimbledon:Strawberries, Glastonbury:Mud, Eurovision:Points, Oktoberfest:Steins, Carnival:Costumes, Halloween:Costumes and sweets, Christmas:Presents, Easter:Eggs, Bonfire Night:Fireworks, New Year's Eve:Countdown, Valentine's Day:Roses, Birthday party:Presents and cake, Wedding:Vows, Honeymoon:Newlyweds, Baby shower:Gifts, Stag do:Groom, Hen party:Bride, Graduation:Gown, Job interview:Nervous, First date:Butterflies, Road trip:Playlist, Camping trip:Outdoors, School trip:Coach, Sleepover:Pyjamas, Barbecue:Grill, Picnic:Blanket, Festival:Tents, Concert:Encore, Parade:Floats, Fireworks:Bang",
  Activities:
    "Painting:Colours, Drawing:Sketch, Knitting:Needles, Sewing:Thread, Baking:Oven, Cooking:Recipe, Gardening:Soil, Reading:Pages, Writing:Words, Photography:Shutter, Singing:Notes, Dancing:Rhythm, Juggling:Balls, Magic tricks:Illusion, Origami:Folding, Pottery:Clay, Woodwork:Chisel, Fishing trip:Patience, Birdwatching:Binoculars, Stargazing:Night, Hiking:Trail, Jogging:Pace, Camping:Tent pegs, Sunbathing:Tan, Shopping:Bags, Window shopping:Looking, Online shopping:Basket, Gaming:Controller, Streaming:Live, Binge-watching:Episodes, Podcasting:Episodes and chat, Blogging:Posts, Vlogging:Camera, Selfie:Pose, Karaoke night:Duets, Board games:Dice, Pub quiz:Teams, Crossword:Clues, Sudoku:Grid, Word search:Hidden, Colouring in:Crayons, Scrapbooking:Memories, Collecting stamps:Album, Metal detecting:Beeping, Geocaching:Hunt, Volunteering:Helping, Meditation:Calm, Daydreaming:Distant, Napping:Short sleep, Sleepwalking:Wandering, Snoring:Noisy, Sneezing:Bless you, Hiccups:Jumpy, Yawning:Tired, Whistling:Tune, Tickling:Laughing, High five:Slap, Handshake:Greeting, Hug:Arms, Wink:Eye, Thumbs up:Approval, Queueing:Patience, Commuting:Rush hour, Traffic jam:Stuck, Speed bump:Slow down, Parking ticket:Fine, Flat tyre:Puncture, Car boot sale:Bargains, Garage sale:Selling, Spring cleaning:Declutter, Laundry:Clothes, Washing up:Suds, Moving house:Boxes, Flat-pack furniture:Allen key, DIY:Tools, Decorating:Paint, Wallpapering:Paste, Brushing teeth:Minty, Taking a shower:Water, Getting dressed:Clothes on, Alarm snoozing:Five more minutes, Breakfast in bed:Tray",
  Entertainment:
    "Superhero:Cape, Villain:Evil, Zombie:Undead, Vampire:Fangs, Werewolf:Moonlight, Ghost:Boo, Witch:Broomstick, Wizard:Spells, Dragon:Fire breathing, Unicorn:Horn, Mermaid:Tail, Fairy:Wings, Elf:Pointy ears, Goblin:Green, Troll:Bridge, Giant:Huge, Robot:Metal, Alien:Outer space, UFO:Saucer, Time machine:Travel, Magic wand:Spell, Crystal ball:Fortune, Treasure chest:Gold, Treasure map:X marks, Pirate ship:Jolly Roger, Haunted castle:Spooky, Spaceship:Stars, Lightsaber:Glowing, Invisibility cloak:Vanish, Flying carpet:Magic, Genie:Three wishes, Magic lamp:Rub, Secret agent:Mission, Ninja:Stealth, Samurai:Katana, Cowboy:Lasso, Viking:Longship, Gladiator:Arena, Caveman:Club, Mummy:Bandages, Skeleton:Bones, Scarecrow:Crows, Snow White:Apple, Cinderella:Slipper, Santa Claus:Sleigh, Easter Bunny:Eggs, Tooth fairy:Pillow, Sherlock Holmes:Magnifier, Cartoon:Animated, Anime:Japanese, Comic book:Panels, Video game:Console, Board game:Pieces, Quiz show:Questions, Game show:Prizes, Reality TV:Drama, Soap opera:Episodes, Documentary:Facts, Horror film:Scary, Romcom:Love story, Musical:Songs, Opera:Singing, Ballet:Tutu, Stand-up comedy:Microphone, Talent show:Judges, Red carpet:Celebrities, Oscar:Award, Paparazzi:Cameras, Autograph:Signature, Selfie stick:Pole, Emoji:Face, Meme:Funny, Hashtag:Symbol, Password:Secret, Wi-Fi:Signal, Bluetooth:Wireless, Charger:Plug, Power bank:Portable, Smartwatch:Wrist, Drone:Flying camera, Virtual reality:Headset, Artificial intelligence:Clever computer, Smart speaker:Voice, Printer:Ink, Keyboard:Keys, Mouse:Click, Webcam:Video call, Speaker:Loud, Microphone:Voice, Vinyl record:Needle, Cassette:Tape, Jukebox:Coins, Arcade machine:High score, Pinball:Flippers, Slot machine:Jackpot, Lottery ticket:Numbers, Scratch card:Coin",
  Clothing:
    "T-shirt:Short sleeves, Jumper:Knitted, Hoodie:Pullover, Jacket:Zip, Coat:Winter, Raincoat:Waterproof, Suit:Formal, Tie:Knot, Bow tie:Dapper, Dress:Party, Skirt:Waist, Jeans:Denim, Shorts:Summer, Pyjamas:Bedtime, Dressing gown:Fluffy, Slippers:Indoors, Trainers:Laces, Flip-flops:Beach, Wellies:Puddles, High heels:Tall, Boots:Ankles, Sandals:Toes, Socks:Pairs, Tights:Legs, Hat:Head, Cap:Peak, Beanie:Woolly, Scarf:Neck, Gloves:Fingers, Mittens:No fingers, Belt:Buckle, Braces:Straps, Swimsuit:Pool, Bikini:Two piece, Wetsuit:Neoprene, Onesie:All in one, Tutu:Ballet, Apron:Cooking, Uniform:Matching, Crown:Royal, Tiara:Princess, Wig:Fake hair, Mask:Face, Costume:Fancy dress, Kilt:Scotland, Poncho:Blanket, Cape:Flowing, Cowboy hat:Wide brim, Top hat:Magician, Hard hat:Safety, Helmet:Protection, Earrings:Lobes, Necklace:Chain, Bracelet:Wrist, Ring:Finger, Engagement ring:Proposal, Handbag:Carry, Bum bag:Waist pouch, Lipstick:Makeup, Nail varnish:Polish, Perfume:Scent, Tattoo:Permanent, Beard:Chin, Moustache:Upper lip, Ponytail:Hair tie, Mohawk:Punk, Bald head:Shiny, Freckles:Spots, Dimples:Cheeks",
  Everyday:
    "Monday morning:Groan, Weekend:Freedom, Holiday:Time off, Lie-in:Late, Hangover:Regret, Brain freeze:Too fast, Pins and needles:Tingling, Déjà vu:Again, Goosebumps:Chilly, Butterflies in stomach:Nerves, Jet lag:Time zones, Sunburn:Red skin, Mosquito bite:Itch, Paper cut:Ouch, Stubbed toe:Furniture, Bad hair day:Messy, Awkward silence:Crickets, Group chat:Notifications, Voice note:Recording, Unread messages:Ignoring, Low battery:Red icon, Lost keys:Searching, Missed bus:Running, Surprise party:Shh, Secret Santa:Gift swap, Christmas jumper:Festive, Advent calendar:Doors, Pancake Day:Tossing, April Fools:Pranks, Tooth brushing:Twice a day, Dentist appointment:Check-up, Driving test:Examiner, Exam:Revision, Homework:Due, Detention:After school, Lunch break:Midday, Fire drill:Alarm, Coffee break:Mug, Office party:Colleagues, Payday:Salary, Tax return:Paperwork, Parking space:Spot, Queue jumper:Rude, Sat nav:Directions, Speed camera:Flash, Toll road:Pay, Vending machine:Snacks, Cash machine:PIN, Self-checkout:Unexpected item, Loyalty card:Points, Meal deal:Lunch, Takeaway:Delivery, Delivery driver:Parcel, Doorstep:Outside, Neighbour:Next door, Landlord:Rent, Housemate:Sharing, Best friend:Closest, Grandma:Knitting, Grandad:Stories, Twins:Identical, Baby:Nappy, Toddler:Tantrum, Teenager:Moody, Pensioner:Retired, Pet shop:Animals, Dog walker:Leads, Babysitter:Evening, Tour guide:Umbrella, Travel agent:Bookings, Passport:Photo, Boarding pass:Gate, Duty free:Airport, Souvenir:Keepsake, Postcard:Wish you were here, Sunscreen:Factor, Beach towel:Lying down, Sandcastle:Bucket, Deckchair:Stripes, Lilo:Inflatable, Rock pool:Crabs, Pier:Seaside, Arcade:Coins, Candy shop:Sweets, Ice rink:Skates, Wax museum:Figures, Botanical garden:Plants, Planetarium:Dome, Observatory:Stars",
  Music:
    "Guitar:Strings, Electric guitar:Amp, Bass guitar:Low, Piano:Keys, Keyboard piano:Electric, Drums:Sticks, Violin:Bow, Cello:Between knees, Double bass:Huge, Harp:Angelic, Trumpet:Brass, Trombone:Slide, Saxophone:Jazz, Clarinet:Reed, Flute:Blow, Recorder:School, Harmonica:Mouth, Accordion:Squeeze, Bagpipes:Scotland, Ukulele:Small, Banjo:Country, Tambourine:Shake, Triangle:Ding, Xylophone:Bars, Maracas:Rattle, Bongos:Hands, Orchestra:Symphony, Conductor:Baton, Choir:Voices, Rock band:Loud, Boy band:Screaming fans, Girl band:Harmonies, Rapper:Rhymes, Beatbox:Mouth sounds, Headbanging:Metal, Mosh pit:Pushing, Crowd surfing:Carried, Air guitar:Pretend, Encore:One more, Soundcheck:Testing, Backstage:Behind, Tour bus:On the road, Busker:Street, National anthem:Standing, Lullaby:Sleep, Nursery rhyme:Children, Ringtone:Calling, Playlist:Songs, Album:Tracks, Music video:Watch",
};

const seen = new Set();
export const WORDS = [];
for (const [theme, text] of Object.entries(THEMES)) {
  for (const raw of text.split(",")) {
    const [w, h] = raw.split(":");
    const word = (w || "").trim();
    const hint = (h || "").trim();
    const key = word.toLowerCase();
    if (!word || seen.has(key)) continue;
    seen.add(key);
    WORDS.push({ word, hint, theme });
  }
}
